<a href="https://colab.research.google.com/github/mohdshahbaaz059/numpy/blob/main/Dimension_And_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***dimension method***

In [ ]:
import numpy as  np

In [ ]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


***o-dimension***

In [7]:
import numpy as np

arr = np.array(45)

print(arr)

45


***1-dimension***


In [9]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


***2-dimension***


In [10]:
import numpy as np

arr = np.array([1,2,3,4,5]),([6,7,8,9,10])

print(arr)

(array([1, 2, 3, 4, 5]), [6, 7, 8, 9, 10])


***3-dimension***

In [12]:
import numpy as np

arr = np.array([1,2,3]),([4,5,6]),([7,8,9])

print(arr)

(array([1, 2, 3]), [4, 5, 6], [7, 8, 9])


***N-dimension***

In [18]:
import numpy as np

a = np.array(10)
b = np.array([1,2,3])
d = np.array([[1,2,3],[4,5,6]])
e = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3


***Higher Dimension  array***



In [21]:
import numpy as np

arr = np.array([1,2,3,4],ndmin=5)

print(arr)
print('number of dimension:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimension: 5


***numpy array indexing***



In [24]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr[0])

1


***2-element***


In [29]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr[1])

2


***Adding both element***

In [28]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr[2] + arr[3])

7
