<a href="https://colab.research.google.com/github/mohdshahbaaz059/numpy/blob/main/RAMDOM_IN_NUMPY_ipnb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from numpy import random

x = random.randint(100)

print(x)

45


In [4]:
from numpy import random

x = random.rand()

print(x)

0.577466470126679


In [5]:
from numpy import random

x = random.randint(100, size=(5))


print(x)


[99 76  6 10 44]


In [7]:
from numpy import random

x = random.randint(100, size=(3,5))

print(x)

[[42 12 82 45 91]
 [ 3 16  2 36 34]
 [38 96  5 90 31]]


In [9]:
from numpy import random

x = random.rand(5)

print(x)

[0.96067158 0.07956098 0.5378086  0.6980185  0.22158224]


In [11]:
from numpy import random

x = random.rand(3,5)

print(x)

[[0.84790539 0.19757553 0.68358697 0.56287933 0.72720425]
 [0.61708747 0.80126757 0.70520663 0.68294976 0.51476668]
 [0.08409498 0.63141973 0.53904107 0.34655082 0.86709057]]


In [12]:
from numpy import random

x = random.choice([3,4,5,6])

print(x)

4


In [16]:
from numpy import random

x = random.rand(3,4,5,6,7)

print(x)

[[[[[0.68242667 0.52437435 0.55035114 ... 0.67762799 0.22629412
     0.68252723]
    [0.34009787 0.54989102 0.57735273 ... 0.55233765 0.7826792
     0.3002438 ]
    [0.39990659 0.12185511 0.34916064 ... 0.71095716 0.22054806
     0.12676477]
    [0.0770431  0.44679601 0.95911377 ... 0.7710412  0.69148044
     0.31649436]
    [0.62507454 0.59117147 0.09697765 ... 0.76337214 0.34352532
     0.44856794]
    [0.53659753 0.1442865  0.26243531 ... 0.60635198 0.79369271
     0.57773246]]

   [[0.65783639 0.3651954  0.12106058 ... 0.87861397 0.93431771
     0.50905818]
    [0.76623596 0.68110537 0.345042   ... 0.48702492 0.48591749
     0.01571975]
    [0.37018887 0.37909765 0.48819969 ... 0.61626975 0.79421129
     0.55530578]
    [0.03117074 0.44938685 0.74261655 ... 0.40639093 0.88929486
     0.38545358]
    [0.97880682 0.93748641 0.81327623 ... 0.43098936 0.41569115
     0.62040423]
    [0.91614877 0.94298596 0.23270641 ... 0.94759377 0.00223817
     0.83867945]]

   [[0.56681095 0.0248336

In [22]:
from numpy import random

x = random.choice([3,4,5,6], size=(3,5))

print(x)

[[4 4 4 3 5]
 [6 3 3 4 3]
 [6 4 3 4 3]]


In [23]:
from numpy import random

x = random.choice([3,4,5,9], p=[0.1,0.3,0.6,0.0])

print(x)

5


In [24]:
from numpy import random

x = random.choice([3,4,5,9], p=[0.1,0.3,0.6,0.0], size=(3,5))

print(x)

[[4 5 5 4 4]
 [5 5 4 5 5]
 [4 5 3 5 4]]


In [26]:
from numpy import random
import numpy as np

arr = np.array([1,2,3,4,5])

random.shuffle(arr)

print(arr)

[3 5 1 4 2]


In [27]:
from numpy import random
import numpy as np

arr = np.array([1,2,3,4,5])

print(random.permutation(arr))

[4 2 5 3 1]
